export enum RuleId {
  GameSetupHandMulligan = 1,
  GameSetupPlaceTerritoryTokens,
  GameSetupRiver,
  PrimaryProduction,
  ChooseAction,
  ExpansionChooseCube,
  ExpansionPlaceTokenOnMountain,
  ExpansionPlaceTokenOnForest,
  ExpansionPlaceTokenOnMeadow,
  ExpansionPlaceTokenOnWetland,
  AdaptationAction,
  EndOfCycle,
  EvolutionActionPlaceCubesAndDiscardCards,
  EvolutionActionPickCards,
  EvolutionActionDiscardCardsFromHand,
  MigrationActionChooseCube,
  MigrationActionMoveTerritoryTokenOnMountain,
  MigrationActionMoveTerritoryTokenOnForest,
  MigrationActionMoveTerritoryTokenOnMeadow,
  MigrationActionMoveTerritoryTokenOnWetland,
}
