export enum LocationType {
  EcosystemBoardSpot = 1,
  TerritoryTokenSpotOnEcosystemBoard,
  CubeSpotOnEcosystemBoard,
  PlayerBiotopesCardSpot,
  PlayerSpeciesCardTableauSpot,
  PlayerInitiativeTokenSpot,
  CubeSpotOnPlayerBiotopesCard,
  CubeSpotOnPlayerSpeciesCard,
  EnvironmentalConditionsBoardSpot,
  EnvironmentalConditionTokenSpotOnEnvironmentalConditionsBoard,
  CycleTokenSpotOnEnvironmentalConditionsBoard,
  SpeciesDecksSpot,
  SpeciesRiversGrid,
  SpeciesDiscardsSpot,
  CentralLandscapeSpot,
  PlayerSpeciesCardHandSpot,
  CubeStockpileSpot,
  RecycledCubesSpot,
  BiotopeBoardSelectionSpot,
  BiotopeBoardSpot,
  CubeOnBiotopeBoardSpot
}
