export enum SpeciesCardEffect {
  FecundSpecies = 1,
  CosmopolitanSpecies,
  PollinatingSpecies,
  ForestSpecies,
  GranivorousSpecies,
  PartialMigrator,
  MountainSpecies,
  AquaticSpecies,
  WoodlandSpecies,
  MeadowSpecies,
  RockSpecies,
  AmphibianSpecies,
  WidespreadSpecies,
  MigratingSpecies,
  DetritivoreSpecies,
  RSelectedSpecies,
  TerritorialSpecies,
  Patroller,
  AdaptativeIntelligence,
  DiscreetSpecies
}
